version: '3.5'

services:
  db:
    image: postgres:11.5
    ports:
      - 5432:5432
    container_name: loan-db
    environment:
      POSTGRES_USER: "${DB_USERNAME:-loan}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-Ivy_890}"
    volumes:
      - dbdata:/var/lib/postgresql/dbdata

  nginx: 
    image: nginx:latest
    container_name: loan-nginx
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./config/nginx/default:/usr/share/nginx/html/
    ports:
      - 443:443
      - 80:80
    extra_hosts:
       - "outside:172.17.0.1"
    depends_on:
      - db
      - pgadmin
    environment:
      TLOC_WEB_HOST: "${LOAN_WEB_HOST:-loan-web}"
      TLOC_WEB_PORT: "${LOAN_WEB_PORT:-80}"

      IDENTITY_WEB_HOST: "${IDENTITY_WEB_HOST:-identity-web}"
      IDENTITY_WEB_PORT: "${IDENTITY_WEB_PORT:-80}"

    command: >
      /bin/bash -c "
      cat > /etc/nginx/conf.d/app.conf &&
      cat > /etc/nginx/conf.d/default.conf &&
      envsubst '$$TLOC_WEB_HOST $$TLOC_WEB_PORT $$IDENTITY_WEB_HOST $$IDENTITY_WEB_PORT' </etc/nginx/conf.d/app.template> /etc/nginx/conf.d/app.conf &&
      exec nginx -g 'daemon off;'"
    networks:
      default:
        aliases:
          - loan-local.com
          - web.loan-local.com
          - pgadmin.loan-local.com
          - identity.loan-local.com

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 7999:80
    container_name: loan-pgadmin
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DB_USERNAME:-admin@loan.com}"
      PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD:-Ivy_890}"

 
  loan-web:
    image: loan
    build:
      context: ./App
      dockerfile: Dockerfile
    container_name: loan
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiConfiguration__BaseUrl=http://web.loan-local.com
      
    depends_on:
      - db
    ports:
      - 8090:80
    networks:
      default:
        aliases:
          - loan-web

  identity-web:
    image: identity-server
    build:
      context: ./Identity
      dockerfile: Dockerfile
    container_name: identity-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiConfiguration__BaseUrl=http://identity.loan-local.com
      
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8000:80
    networks:
      default:
        aliases:
          - identity-web
volumes:
  dbdata:
    driver: local
  sqldbdata:
    driver: local

networks:
  default:
    driver: bridge
